[package]
name = "modman"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
modman-pak = { path = "../modman-pak" }
modman-core = { path = "../modman-core" }
serde_json.workspace = true
