name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.cargo/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/rust-build.yml'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/rust-build.yml
